CodingCalendarViewModel unit test
Njack-IITP/IITP-Connect pull request #180
Opened 2018-10-21 17:44 UTC by jguerrerope

**Fixes** #178 
First steps for issues #60 

**Changes:** 

- added library for arch unit test and test for CodingCalendarViewModel

2018-10-21 20:05 UTC, dr0pdb requested changes

2018-10-21 20:05 UTC, srv-twry commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +    public void shouldLoadContest_whenCurrentContestIsNotNull() {
Please use Camel Casing.

2018-10-21 20:05 UTC, srv-twry commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +    public void shouldLoadContest_whenCurrentContestIsNull() {
Camel casing please.

2018-10-21 20:05 UTC, srv-twry commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +
remove one blank line.

2018-10-21 20:22 UTC, jguerrerope commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +    public void shouldLoadContest_whenCurrentContestIsNotNull() {
https://dzone.com/articles/7-popular-unit-test-naming

2018-10-21 20:22 UTC, jguerrerope commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +    public void shouldLoadContest_whenCurrentContestIsNull() {
https://dzone.com/articles/7-popular-unit-test-naming

2018-10-22 03:59 UTC, dr0pdb commented on app/src/test/java/com/iitp/njack/iitp_connect/core/calendar/detail/ContestDetailViewModelTest.java
> +    public void shouldLoadContest_whenCurrentContestIsNull() {
Yes, I am asking you to do it like the point 3. `shouldLoadContestWhenCurrentContestIsNull`.

2018-10-22 19:21 UTC, jguerrerope commented
updated.

2018-10-23 05:44 UTC, dr0pdb approved these changes

2018-10-23 05:45 UTC, merged