CodingCalendarViewmodel unit test
Njack-IITP/IITP-Connect pull request #181
Opened 2018-10-21 17:52 UTC by jguerrerope

Fixes #178
**Changes:**

- change RateLimiter to provide read and write methods and to perform better unit testing
- added coding calendar viewmodel unit test

2018-10-21 20:07 UTC, dr0pdb requested changes
Remove unrelated changes. Rest looks good.

2018-10-21 20:07 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/DaoModule.java
> +    @Provides
The changes in this file are unrelated to the PR. Please don't make unrelated changes. It makes it difficult to find the source of bugs later on.

2018-10-21 20:07 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/NetworkModule.java
> -
Unrelated change.

2018-10-21 20:21 UTC, jguerrerope commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/DaoModule.java
> +    @Provides
using the android/java community standard related class format make your repository more easy to read and contribute. But deal with you 👍

2018-10-21 20:21 UTC, jguerrerope commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/NetworkModule.java
> -
the same as before

2018-10-22 04:01 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/DaoModule.java
> +    @Provides
You can create a new issue for and do it. Please revert these unnecessary changes in this PR.

2018-10-22 04:01 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/DaoModule.java
> +    @Provides
You can create a new issue for and do it. Please revert these unnecessary changes in this PR.

2018-10-22 04:02 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/DaoModule.java
> +    @Provides
You can create a new issue for and do it. Please revert these unnecessary changes in this PR.

2018-10-22 19:21 UTC, jguerrerope commented
updated.

2018-10-24 18:16 UTC, dr0pdb approved these changes

2018-10-24 18:17 UTC, merged