Timetable
Njack-IITP/IITP-Connect pull request #192
Opened 2018-10-28 07:02 UTC by ravi-kishan

First steps for #144 

Changes: Implemented timetable feature in app.
TODO: UI modification

2018-10-28 12:00 UTC, dr0pdb requested changes
@ravi-kishan Please fix the codacy issues.

2018-10-30 19:13 UTC, dr0pdb requested changes

2018-10-30 19:13 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/profile/ProfileActivity.java
> +        ArrayAdapter<CharSequence> yearAdapter;
Don't do this. The previous one was correct. This is not desirable.

2018-10-31 14:52 UTC, dr0pdb requested changes

2018-10-31 14:52 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/profile/ProfileRepository.java
> +    private FirebaseDatabaseLiveData firebaseDatabaseLiveData;
Make it public. It is causing the build failure.

2018-10-31 14:53 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/timetable/TimeTableActivity.java
> +    TimeTableViewModel timeTableViewModel;
@ravi-kishan Make it private.

2018-10-31 14:59 UTC, ravi-kishan commented on app/src/main/java/com/iitp/njack/iitp_connect/core/timetable/TimeTableActivity.java
> +    TimeTableViewModel timeTableViewModel;
Dagger inject does not work on private fields.

2018-10-31 16:29 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/timetable/TimeTableActivity.java
> +    TimeTableViewModel timeTableViewModel;
Ok, then make it public. Explicitly mention it.

2018-10-31 16:29 UTC, srv-twry commented
check the build and fix it.

2018-11-01 15:33 UTC, dr0pdb approved these changes

2018-11-01 15:33 UTC, merged