Add Youtube repositories
Njack-IITP/IITP-Connect pull request #211
Opened 2018-11-30 20:19 UTC by BVShe001

First steps for issues #119 
Changes:Add playlist and video repositories ,fetching data with api and storing them in playlist and video models.

2018-12-01 10:23 UTC, dr0pdb requested changes
Go through the codacy issues and fix them. Also look at why the build is failing and fix it.

2018-12-01 13:10 UTC, BVShe001 commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/VideoRepository.java
> +                public void onComplete() {
Observer requires this method to be implemented.

2018-12-01 13:10 UTC, BVShe001 commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/PlaylistRepository.java
> +                public void onSubscribe(Disposable d) {
Observer requires this method to be implemented.

2018-12-01 13:10 UTC, BVShe001 commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/PlaylistRepository.java
> +                public void onComplete() {
Observer requires this method to be implemented.

2018-12-01 13:10 UTC, BVShe001 commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/VideoRepository.java
> +                public void onSubscribe(Disposable d) {
Observer requires this method to be implemented.

2018-12-01 13:11 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/PlaylistRepository.java
> +                public void onComplete() {
For empty body add a comment such as `// nothing here`.

2018-12-01 13:12 UTC, srv-twry commented
@BVShe001 I know that those empty methods are required but Codacy is suggesting you to **document** it not remove it. Add a comment like `nothing here` inside the method body.

2018-12-01 17:34 UTC, BVShe001 commented
Build is failing because it is no getting api key which I have abstracted as in :
[ how to hide](https://medium.com/code-better/hiding-api-keys-from-your-android-repository-b23f5598b906)

2018-12-04 10:04 UTC, srv-twry commented
@BVShe001 
1. If we're going to let the build fail now and merge this one then all the future builds will fail. Then what's the point of these CI's?
2. Search for how to setup demo api-key on Travis so that the build doesn't fail.

2018-12-04 12:24 UTC, dr0pdb requested changes

2018-12-04 12:24 UTC, dr0pdb commented on .travis.yml
> +  - platform-tools
What have you done here? Don't make unnecessary changes.

2018-12-14 09:37 UTC, dr0pdb requested changes

2018-12-14 09:37 UTC, srv-twry commented on app/build.gradle
> +    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'
Why decrease the version?

2018-12-14 09:37 UTC, srv-twry commented on app/build.gradle
> +    testImplementation 'org.mockito:mockito-inline:2.23.0'
Why decrease it?

2018-12-14 09:37 UTC, srv-twry commented on app/build.gradle
> -    })
Why remove it?

2018-12-14 09:37 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/models/YoutubePlaylist.java
> +    }
Please take a look at other model classes. These getters, setters, constructors can easily be done using annotations such as `@data`, `@allargsconstructor` etc. Use them.

2018-12-14 09:37 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/models/YoutubeVideo.java
> +    }
Check other models.

2018-12-14 09:37 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/PlaylistRepository.java
> +    private String channelName = "GoogleDevelopers";
What is this?

2018-12-14 09:37 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/PlaylistRepository.java
> +        service = new YouTube.Builder(
Use Dagger for it. Create an instance of YouTube builder and inject it in the Repository as a dependency just like `GoogleAccountCredential`.

2018-12-14 09:37 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/repositories/VideoRepository.java
> +        service = new YouTube.Builder(
Use Dagger.

2018-12-14 11:04 UTC, sheetal-g9 commented on app/build.gradle
> -    })
It is redundant.Same dependency is used at line :170 with a newer version 3.0.1

2018-12-14 13:49 UTC, dr0pdb requested changes

2018-12-14 13:49 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/YoutubeModule.java
> +        return new PlaylistRepository();
Don't use DI for providing repository. Revert this back to what it was.

2018-12-14 13:49 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/YoutubeModule.java
> +        return new VideoRepository();
Same here.

2018-12-14 13:49 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/common/di/modules/YoutubeModule.java
> +    }
Add an extra line!

2018-12-14 20:12 UTC, closed without merging