Implement Video Dao and Repository
Njack-IITP/IITP-Connect pull request #245
Opened 2019-01-08 13:43 UTC by BVShe001

First steps for issues #119 
Changes: Add Video Data Access Object and VideoRepository

2019-01-08 16:16 UTC, dr0pdb requested changes

2019-01-08 16:16 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/video/VideoRepository.java
> +        if (videos.getValue() == null || videos.getValue().isEmpty() || repoListRateLimit.shouldFetchAndRefresh(VIDEOS)) {
@BVShe001 Change this to 
`return (videos.getValue() == null || videos.getValue().isEmpty() || repoListRateLimit.shouldFetchAndRefresh(VIDEOS));`

2019-01-08 16:16 UTC, srv-twry commented on app/src/main/java/com/iitp/njack/iitp_connect/core/youtube/video/VideoRepository.java
> +                    e.printStackTrace();
Use Timber please.

2019-01-09 08:00 UTC, dr0pdb approved these changes

2019-01-10 12:42 UTC, ravi-kishan approved these changes

2019-01-11 14:14 UTC, merged